import React,{useEffect,useMemo,useState}from'react';
import{Alert,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{SafeAreaProvider,SafeAreaView}from'react-native-safe-area-context';import{StatusBar}from'expo-status-bar';
import{defaultMenu,normalizeMenu}from'./src/data/menu';import{defaultSettings,mergeSettings}from'./src/data/settings';
import{NewOrderScreen}from'./src/screens/NewOrderScreen';import{OrdersScreen}from'./src/screens/OrdersScreen';import{SettingsScreen}from'./src/screens/SettingsScreen';import{DashboardScreen}from'./src/screens/DashboardScreen';import{AppErrorBoundary}from'./src/components/AppErrorBoundary';
import{STORAGE_KEYS,loadJson,saveJson,saveAutomaticBackup}from'./src/utils/storage';import{localDateKey}from'./src/utils/reports';import{theme}from'./src/theme';
export default function App(){return <AppErrorBoundary><SafeAreaProvider><Shell/></SafeAreaProvider></AppErrorBoundary>}
function Shell(){const[tab,setTab]=useState('new'),[menu,setMenu]=useState(defaultMenu),[orders,setOrders]=useState([]),[settings,setSettings]=useState(defaultSettings),[loyalty,setLoyalty]=useState({}),[ready,setReady]=useState(false);
useEffect(()=>{(async()=>{try{const m=normalizeMenu(await loadJson(STORAGE_KEYS.menu,defaultMenu));const o=await loadJson(STORAGE_KEYS.orders,[]);const s=mergeSettings(await loadJson(STORAGE_KEYS.settings,defaultSettings));const l=await loadJson(STORAGE_KEYS.loyalty,{});setMenu(m);setOrders(o);setSettings(s);setLoyalty(l);await saveAutomaticBackup(m,o,s,l)}catch(e){Alert.alert('Load error','Saved data could not be loaded.')}finally{setReady(true)}})()},[]);
async function saveMenu(v){const n=normalizeMenu(v);setMenu(n);await saveJson(STORAGE_KEYS.menu,n)}async function saveSettings(v){const n=mergeSettings(v);setSettings(n);await saveJson(STORAGE_KEYS.settings,n)}
async function addOrder(o){const n=[o,...orders];setOrders(n);await saveJson(STORAGE_KEYS.orders,n);if(o.loyalty?.phone&&o.loyalty?.program){const phone=o.loyalty.phone.replace(/\s/g,'');const old=loyalty[phone]||{name:o.customerName||'',coffee:0,meal:0};const key=o.loyalty.program.toLowerCase();const next={...loyalty,[phone]:{...old,name:o.customerName||old.name,[key]:Number(old[key]||0)+1}};setLoyalty(next);await saveJson(STORAGE_KEYS.loyalty,next)}}
function nextNo(now=new Date()){const k=localDateKey(now);return String(orders.filter(o=>(o.dayKey||localDateKey(o.createdAt))===k).length+1).padStart(3,'0')}
async function restore(p){const m=normalizeMenu(p.menu||defaultMenu),o=Array.isArray(p.orders)?p.orders:[],s=mergeSettings(p.settings||defaultSettings),l=p.loyalty||{};setMenu(m);setOrders(o);setSettings(s);setLoyalty(l);await Promise.all([saveJson(STORAGE_KEYS.menu,m),saveJson(STORAGE_KEYS.orders,o),saveJson(STORAGE_KEYS.settings,s),saveJson(STORAGE_KEYS.loyalty,l)]);Alert.alert('Backup restored','Menu, settings, sales and loyalty data restored.')}
const content=useMemo(()=>{if(!ready)return <View style={st.load}><Text>Loading...</Text></View>;if(tab==='dash')return <DashboardScreen orders={orders}/>;if(tab==='sales')return <OrdersScreen orders={orders} settings={settings}/>;if(tab==='settings')return <SettingsScreen menu={menu} onSaveMenu={saveMenu} settings={settings} onSaveSettings={saveSettings} orders={orders} onRestoreBackup={restore}/>;return <NewOrderScreen menu={menu} onSaveMenu={saveMenu} settings={settings} onSaveSettings={saveSettings} loyalty={loyalty} onOrderSaved={addOrder} getNextOrderNumber={nextNo}/>},[tab,menu,orders,settings,loyalty,ready]);
return <SafeAreaView style={st.safe}><StatusBar style="light" backgroundColor={theme.colors.espresso}/><View style={st.header}><View style={st.logo}><Text style={st.logoText}>FG</Text></View><View style={{flex:1}}><Text style={st.brand}>FRESHLY GROUND</Text><Text style={st.express}>EXPRESS</Text></View><Text style={st.usb}>{settings.printer?'USB READY':'USB SETUP'}</Text></View><View style={{flex:1,backgroundColor:theme.colors.bg}}>{content}</View><View style={st.tabs}><Tab a={tab==='new'} t="New Order" on={()=>setTab('new')}/><Tab a={tab==='dash'} t="Dashboard" on={()=>setTab('dash')}/><Tab a={tab==='sales'} t="Sales" on={()=>setTab('sales')}/><Tab a={tab==='settings'} t="Settings" on={()=>setTab('settings')}/></View></SafeAreaView>}
function Tab({a,t,on}){return <TouchableOpacity onPress={on} style={[st.tab,a&&st.tabA]}><Text style={st.tabT}>{t}</Text></TouchableOpacity>}
const c=theme.colors,st=StyleSheet.create({safe:{flex:1,backgroundColor:c.espresso},header:{minHeight:72,padding:12,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:c.espresso},logo:{width:44,height:44,borderRadius:22,backgroundColor:c.green,alignItems:'center',justifyContent:'center'},logoText:{color:'#fff',fontWeight:'900'},brand:{color:'#fff',fontWeight:'900',fontSize:17},express:{color:'#D75A50',fontWeight:'900',letterSpacing:3},usb:{color:'#fff',backgroundColor:c.green,padding:7,borderRadius:20,fontSize:9,fontWeight:'900'},tabs:{flexDirection:'row',gap:6,padding:7,backgroundColor:c.espresso},tab:{flex:1,padding:9,borderRadius:10,alignItems:'center'},tabA:{backgroundColor:c.green},tabT:{color:'#fff',fontWeight:'900'},load:{flex:1,alignItems:'center',justifyContent:'center'}});
