import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';
import * as DocumentPicker from 'expo-document-picker';
import { formatMoney } from './receiptPrinter';

export function localDateKey(value) {
  const d = value instanceof Date ? value : new Date(value);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export function groupOrdersByDay(orders = []) {
  const map = new Map();
  orders.forEach((order) => {
    const key = order.dayKey || localDateKey(order.createdAt);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(order);
  });
  return [...map.entries()]
    .sort(([a], [b]) => b.localeCompare(a))
    .map(([date, dayOrders]) => ({
      date,
      orders: [...dayOrders].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)),
      total: dayOrders.reduce((sum, order) => sum + Number(order.total || 0), 0),
      count: dayOrders.length,
      average: dayOrders.length ? dayOrders.reduce((sum, order) => sum + Number(order.total || 0), 0) / dayOrders.length : 0,
    }));
}

export function buildSalesSummary(orders = []) {
  const productMap = new Map();
  let total = 0;
  orders.forEach((order) => {
    total += Number(order.total || 0);
    (order.items || []).forEach((item) => {
      const key = item.name;
      const current = productMap.get(key) || { name: item.name, qty: 0, sales: 0 };
      const modifierValue = (item.selectedModifiers || []).reduce((s, m) => s + Number(m.price || 0), 0);
      current.qty += Number(item.qty || 0);
      current.sales += Number(item.qty || 0) * (Number(item.unitPrice || 0) + modifierValue);
      productMap.set(key, current);
    });
  });
  return {
    total,
    count: orders.length,
    average: orders.length ? total / orders.length : 0,
    products: [...productMap.values()].sort((a, b) => b.qty - a.qty),
  };
}

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildDailySalesHtml(date, orders = []) {
  const summary = buildSalesSummary(orders);
  const rows = orders.map((order) => {
    const items = (order.items || []).map((item) => {
      const mods = (item.selectedModifiers || []).map((m) => ` + ${esc(m.name)}`).join('');
      return `${item.qty} x ${esc(item.name)}${mods}${item.note ? ` — ${esc(item.note)}` : ''}`;
    }).join('<br/>');
    return `<tr><td>#${esc(order.number)}</td><td>${esc(order.createdAtText || '')}</td><td>${esc(order.orderType || '')}</td><td>${items}</td><td class="money">${formatMoney(order.total)}</td></tr>`;
  }).join('');

  const products = summary.products.map((p) => `<tr><td>${esc(p.name)}</td><td>${p.qty}</td><td class="money">${formatMoney(p.sales)}</td></tr>`).join('');

  return `<!doctype html><html><head><meta charset="utf-8"><style>
    body{font-family:Arial,sans-serif;color:#1b1a18;padding:28px;font-size:12px}h1{margin:0;color:#214c3c}h2{margin-top:28px}.muted{color:#6d6a63}.cards{display:flex;gap:12px;margin:18px 0}.card{border:1px solid #d8d2c5;border-radius:8px;padding:12px;min-width:140px}.big{font-size:20px;font-weight:700}.money{text-align:right;white-space:nowrap}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border-bottom:1px solid #ddd;padding:7px;text-align:left;vertical-align:top}th{background:#f1eee6}footer{margin-top:30px;color:#777}
  </style></head><body>
    <h1>FRESHLY GROUND EXPRESS</h1><div class="muted">Daily Sales Report — ${esc(date)}</div>
    <div class="cards"><div class="card"><div class="muted">Sales</div><div class="big">${formatMoney(summary.total)}</div></div><div class="card"><div class="muted">Orders</div><div class="big">${summary.count}</div></div><div class="card"><div class="muted">Average Order</div><div class="big">${formatMoney(summary.average)}</div></div></div>
    <h2>Orders</h2><table><thead><tr><th>Order</th><th>Time</th><th>Type</th><th>Items</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table>
    <h2>Products Sold</h2><table><thead><tr><th>Product</th><th>Qty</th><th>Sales</th></tr></thead><tbody>${products}</tbody></table>
    <footer>Generated by Freshly Ground Orders</footer>
  </body></html>`;
}

export async function shareDailySales(date, orders) {
  const { uri } = await Print.printToFileAsync({ html: buildDailySalesHtml(date, orders) });
  const available = await Sharing.isAvailableAsync();
  if (!available) throw new Error('Sharing is not available on this device.');
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Freshly Ground sales ${date}` });
}

export async function shareBackup(payload) {
  const file = new File(Paths.cache, `freshly-ground-backup-${Date.now()}.json`);
  file.create({ overwrite: true, intermediates: true });
  file.write(payload);
  const available = await Sharing.isAvailableAsync();
  if (!available) throw new Error('Sharing is not available on this device.');
  await Sharing.shareAsync(file.uri, { mimeType: 'application/json', dialogTitle: 'Freshly Ground backup' });
}

export async function pickBackup() {
  const result = await DocumentPicker.getDocumentAsync({ type: 'application/json', copyToCacheDirectory: true, multiple: false });
  if (result.canceled || !result.assets?.[0]) return null;
  const file = new File(result.assets[0].uri);
  const text = await file.text();
  return JSON.parse(text);
}
